blank_issues_enabled: true
contact_links:
  - name: r/leanpython
    url: https://www.reddit.com/r/learnpython/
    about: Forum for asking and answering questions about Python
  - name: Stack Overflow
    url: https://stackoverflow.com/questions/tagged/pyinit
    about: Forum for asking and answering programming questions
