blank_issues_enabled: false
contact_links:
  - name: GitHub discussions
    url: https://github.com/felix-hilden/mold/discussions
    about: Mold Q&A and general discussions
  - name: Stack Overflow
    url: https://stackoverflow.com/questions/tagged/pyinit
    about: Forum for programming questions in general
