from . import (
    contributing_py_github,
    github,
    github_actions,
    gitignore_minimal,
    gitignore_python,
    license_mit,
    pytest_tox,
    readme_pypi,
    readme_rst,
    rtd_sphinx,
    setuptools,
    source_basic_py,
    source_cli_py,
    source_mold_plugin,
    sphinx,
    todo_rst,
)
